version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[update github-actions deps]:"
    assignees:
      - "lleitep3"
    target-branch: "develop"
    labels:
      - "ci/cd"
      - "dependencies"

  # Maintain dependencies for web
  - package-ecosystem: "npm"
    directory: "/packages/web"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "[update cardapio-web npm deps]:"
    assignees:
      - "lleitep3"
    target-branch: "develop"
    labels:
      - "web"
      - "dependencies"

  # Maintain dependencies for api
  - package-ecosystem: "npm"
    directory: "/packages/api"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[update cardapio-api npm deps]:"
    assignees:
      - "lleitep3"
    target-branch: "develop"
    labels:
      - "api"
      - "dependencies"
