
version: '3.9'
services:

  server:
    extends:
      file: ./packages/server/docker-compose.yml
      service: server
    networks:
      - proxy-lan


  proxy:
    extends:
      file: ./packages/proxy/docker-compose.yml
      service: proxy
    depends_on:
      - server
    networks:
      - proxy-lan

  web:
    extends:
      file: ./packages/web/docker-compose.yml
      service: web
    networks:
      - proxy-lan


networks:
  proxy-lan:
    external: true
    name: proxy-lan
