version: "3.9"
services:
  #  Web Vite
  web:
    image: cardapio-web
    container_name: cardapio-web
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - ENV=local
    env_file:
      - .env
    ports:
      - "3000:3000"

    volumes:
      - type: bind
        source: .
        target: /app
