version: "3.9"
services:
  api:
    image: cardapio-api-test
    container_name: cardapio-api-test
    build:
      target: test
      dockerfile: Dockerfile
      context: .
    environment:
      - NODE_ENV=test
      - PORT=5000
      - APP_NAME=cardapio-api
    command: [ "yarn", "test" ]
