version: "3.9"
services:
  # API Node
  server:
    image: cardapio-api
    container_name: cardapio-api
    build:
      target: production
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "5000:5000"

    # volumes:
    #   - type: bind
    #     source: ./src
    #     target: /app/src
