version: "3.9"
services:
  # API Node
  api:
    depends_on:
      - local-mongodb

    image: cardapio-api
    container_name: cardapio-api
    build:
      target: local
      dockerfile: Dockerfile
      context: .
      args:
        - PORT=5000
        - APP_NAME=cardapio-api
        - ENV=local
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    networks:
      - proxy-lan

  local-mongodb:
    image: mongo
    container_name: local-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: always
    networks:
      - proxy-lan

volumes:
  mongodata:


networks:
  proxy-lan:
    external: true
    name: proxy-lan
