version: "3.9"
services:
  proxy:
    container_name: proxy
    hostname: proxy
    image: nginx:1-alpine@sha256:6f94b7f4208b5d5391246c83a96246ca204f15eaf7e636cefda4e6348c8f6101
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/includes:/etc/nginx/includes
      - ./logs:/var/log/nginx
    restart: always
