name: cardapio-api Validations

on:
  pull_request:
    types:
      - opened
    branches:
      - "main"
      - "develop"

    paths:
      - "packages/api/**"
      - ".github/workflows/run-api-validations.yml"

jobs:
  validations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: "Build container"
        run: |
          cd packages/api
          docker compose -f ./docker-compose.test.yml up --build --detach --remove-orphans

      - name: "Run lint"
        run: docker run cardapio-api-test yarn lint

      - name: "Run tests"
        run: docker run cardapio-api-test yarn test

  # login-ecr:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Login to ECR
  #       uses: docker/login-action@v2
  #       with:
  #         registry: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION>.amazonaws.com
  #         username: $AWS_ACCESS_KEY_ID
  #         password: $AWS_SECRET_ACCESS_KEY

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         file: ./Dockerfile
  #         args: |
  #           ENV: production
  #         push: true
  #         tags: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION>.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG
